apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: taxi-fare-serving
  namespace: mlops
spec:
  selector:
    matchLabels:
      app: taxi-fare-serving
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
