apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bentoml-serving
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Jinnso/mlops-platform
    path: k8s/bentoml
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
